### ISSUE TITLE
[Epic] Write a joint application to NSF call for building an Open Knowledge Network

### ISSUE THREAD

**Issue by silvianetobessa** [Network-Goods/research-roadmaps#2]
## What

 NSF opened a multi-agency call to build a prototype of an open knowledge graph
Assemble the necessary team, choose a compelling topics,

Deadline for submission: June 20th

## Why
Source of external funding to create a knowledge graph that tests the practical use.

## How

This Epic/Initiative is done when: 
 
🥇 If successful, we receive funding for building a public knowledge graph with the knowledge synthesis and coordination protocols that we've been driving and championing in the past months and get external validation from a national agency.
 
🥈 We align on a strategic vision, team, and plan to create a knowledge graph. We get feedback from a national agency.

- [ ] Evaluate eligibility and ROI for NG
- [ ] Discuss the theme and plan of action with the consortium
- [ ] Reach out to gov agencies for support and/or endorsement letters
- [ ] Write the application
- [ ] Attend office hours (optional)
- [ ] Submit the application

 ## References
  
- [NSF Call](https://www.nsf.gov/pubs/2023/nsf23571/nsf23571.htm)
- [Slack Thread](https://www.google.com/url?q=https://protocollabs.slack.com/archives/C04NKKXPLGZ/p1679579826183499&sa=D&source=calendar&ust=1683130604663847&usg=AOvVaw1UU8_QsdzgtAD178FELSPR)
- 📝 [Discourse Graph Heilmeier](https://www.google.com/url?q=https://docs.google.com/document/d/1BI0lkSy0W9kcvtoKcPsT6s5SmDxF6huaR7YPn_Z8rUs/edit%23heading%3Dh.o14tsgedwxsz&sa=D&source=calendar&ust=1683130604663847&usg=AOvVaw1bVR77iX1YUWyu6INa7KpG)
- 📝[Ask Pub Pub Plan](https://www.google.com/url?q=https://docs.google.com/document/d/10tegNdFMKaE2Wph1-BXsPR0nkx4cD1qlrczanRcEZhE/edit%23heading%3Dh.o14tsgedwxsz&sa=D&source=calendar&ust=1683130604663847&usg=AOvVaw2eud6I_ccGnAKOlG2eg2Cr)
- 📲[Metting notes - Silvia and SJ Klein](https://www.notion.so/network-goods/2023-04-27-SB-SJ-OKN-886799259c6d45eb92b8b07090b15380)
- 📲[OKN call agenda](https://docs.google.com/document/d/1bDLynE1y3A6K2KMUjmJ87zm6lIwHH6ZbRxQTwP2ePyE/edit?pli=1#)
