### ISSUE TITLE
[Epic] Disseminate thought leadership for RR

### ISSUE THREAD

**Issue by silvianetobessa** [Network-Goods/research-roadmaps#5]
## How

This Epic/Initiative is done when: 
 
🥇 <high hope>
 
🥈 <base hope>

- [ ] Publish a website
- [ ] Create a public github for documentation
- [ ] Create a Vision Deck
- [ ] Plan a working group / workshop for Roadmaps around EthCC Paris / FtC
- [ ] Write a whitepaper
- [ ] Plan marketing and blogposts 
- [ ] Create branding
- [ ] Present at [Metascience](https://metascience.info/events/research-roadmapping-permissionless-discourse-for-improved-foresight-coordination/) && participate in the [Research Objects ](https://metascience.info/events/linking-shared-research-objects/) panel
- [ ] Attend [Spec Tec workshop on Technical Roadmapping](https://docs.google.com/document/d/1V5ydTYaamb--TSWv_lNTk_lJVrz73prH/edit?rtpof=true&sd=true)

 ## References
  
  - [Website](https://researchroadmaps.ai)
  - Github
  - [Whitepaper draft](https://docs.google.com/document/d/16NjP0pFvxTQwAfSIFn0NW8ozw0DQWXAes2M0Gq2jEKg/edit?usp=drive_web&ouid=104930459343622350578)
